name: password_manager
description: "A new Flutter project."
publish_to: 'none' 
version: 2.0.0+1
environment:
  sdk: '>=3.3.0-48.0.dev <4.0.0'
dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/fg.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true